import { describe,it,expect } from 'vitest';
import { createInventory } from '../src/craft/inventory.ts';
import { assignHauler,buildSite,buyTechnology,collectSite,createEconomy,gather,haulingTraits,recallHauler,restoreEconomy,routeLength,tickEconomy,type Deposit } from '../src/logistics/economy.ts';
import { resourceDeposits,DEPOT } from '../src/logistics/layout.ts';
import type { Roster } from '../src/critters/roster.ts';
import { canAssignToFarm,canMount } from '../src/player/mount.ts';
import { heightAt } from '../src/world/terrain.ts';
const deposits:Deposit[]=[{id:'wood',kind:'wood',pos:{x:30,y:0,z:0},route:[{x:0,y:0,z:0},{x:30,y:0,z:0}]}];
function setup(){const state=createEconomy(deposits),inv=createInventory(),roster:Roster=[{id:1,nickname:'Pip',speciesId:'timberchomp',status:{kind:'idle'}}];return{state,inv,roster,site:state.sites[0]!};}
describe('Haven supply network',()=>{
 it('bootstraps wood and stone by hand, with no capture prerequisite or infinite click exploit',()=>{const {state,site,inv}=setup();gather(state,site,deposits[0]!,inv);gather(state,site,deposits[0]!,inv);expect(inv.wood).toBe(2);expect(site.surveyed).toBe(true);tickEconomy(state,deposits,[],inv,8);gather(state,site,deposits[0]!,inv);expect(inv.wood).toBe(4);});
 it('research requires RP and predecessors, spends only materials, and cannot be bought twice',()=>{const {state,inv}=setup();inv.wood=100;inv.stone=100;inv.fiber=100;inv.resin=100;buyTechnology(state,'fieldworks',inv);expect(state.tech).toEqual([]);inv.rp=25;buyTechnology(state,'harness',inv);expect(state.tech).toEqual([]);buyTechnology(state,'fieldworks',inv);expect(inv.wood).toBe(94);expect(inv.rp).toBe(25);buyTechnology(state,'fieldworks',inv);expect(inv.wood).toBe(94);buyTechnology(state,'harness',inv);expect(state.tech).toContain('harness');});
 it('construction is survey-gated and charges exactly once',()=>{const {state,site,inv}=setup();state.tech=['fieldworks'];inv.wood=8;inv.stone=8;inv.fiber=8;buildSite(state,site,inv);expect(site.built).toBe(false);site.surveyed=true;buildSite(state,site,inv);buildSite(state,site,inv);expect(site.built).toBe(true);expect(inv.wood).toBe(4);});
 it('extractors buffer resources, pause at capacity, and never directly credit inventory',()=>{const {state,site,inv}=setup();site.built=true;tickEconomy(state,deposits,[],inv,600);expect(site.stock).toBe(32);expect(inv.wood).toBe(0);collectSite(site,deposits[0]!,inv);expect(inv.wood).toBe(32);tickEconomy(state,deposits,[],inv,4);expect(site.stock).toBe(0);tickEconomy(state,deposits,[],inv,1);expect(site.stock).toBe(1);});
 it('cargo appears in inventory only after a physical round trip',()=>{const {state,site,inv,roster}=setup();state.tech=['harness'];site.built=true;site.stock=14;assignHauler(state,site,roster,1);tickEconomy(state,deposits,roster,inv,9);expect(site.cargo).toBe(14);expect(inv.wood).toBe(0);expect(site.phase).toBe('homebound');tickEconomy(state,deposits,roster,inv,9);expect(inv.wood).toBe(14);expect(state.delivered).toBe(14);});
 it('recall returns carried cargo to the hopper without material loss or remote delivery',()=>{const {state,site,roster,inv}=setup();state.tech=['harness'];site.built=true;site.stock=14;assignHauler(state,site,roster,1);tickEconomy(state,deposits,roster,inv,9);const total=site.stock+site.cargo;recallHauler(site,roster);expect(site.stock).toBe(total);expect(inv.wood).toBe(0);expect(roster[0]!.status.kind).toBe('idle');});
 it('hauling, farm, and mount jobs are exclusive',()=>{const {state,site,roster}=setup();state.tech=['harness'];site.built=true;assignHauler(state,site,roster,1);expect(canAssignToFarm(roster[0])).toBe(false);expect(canMount(new Set(['saddle']),{...roster[0]!,speciesId:'prismhorse'})).toBe(false);const other={...site,id:'other',worker:null};assignHauler(state,other,roster,1);expect(other.worker).toBeNull();});
 it('upgrades improve their actual bottlenecks and specialists differ from generalists',()=>{expect(haulingTraits('timberchomp','wood').capacity).toBeGreaterThan(haulingTraits('puffle','wood').capacity);const {state,site,inv}=setup();site.built=true;site.level=2;tickEconomy(state,deposits,[],inv,20);expect(site.stock).toBe(8);});
 it('restores an in-flight route without duplicating cargo and repairs orphan assignments',()=>{const {state,site,roster,inv}=setup();state.tech=['harness'];site.built=true;site.surveyed=true;site.stock=14;assignHauler(state,site,roster,1);tickEconomy(state,deposits,roster,inv,9);const restored=restoreEconomy(JSON.parse(JSON.stringify(state)),deposits,roster);expect(restored.sites[0]!.cargo).toBe(14);tickEconomy(restored,deposits,roster,inv,9);expect(inv.wood).toBe(14);restoreEconomy(null,deposits,roster);expect(roster[0]!.status.kind).toBe('idle');});
 it('holds cargo when a constructed obstacle blocks the trail, then resumes',()=>{const {state,site,roster,inv}=setup();state.tech=['harness'];site.built=true;site.stock=14;assignHauler(state,site,roster,1);tickEconomy(state,deposits,roster,inv,9);const distance=site.distance;tickEconomy(state,deposits,roster,inv,100,()=>true);expect(inv.wood).toBe(0);expect(site.distance).toBe(distance);expect(site.cargo).toBe(14);expect(site.blocked).toBe(true);tickEconomy(state,deposits,roster,inv,9,()=>false);expect(inv.wood).toBe(14);});
 it('sanitizes malformed optional logistics data independently',()=>{const {roster}=setup();const state=restoreEconomy({tech:['harness','bogus'],sites:[null,{id:'wood',surveyed:true,built:true,stock:Infinity,cargo:-5,worker:99}]},deposits,roster);expect(state.tech).toEqual(['harness']);expect(state.sites[0]!.stock).toBe(0);});
 it('lays out six dry, walkable trails outside Haven buildings',()=>{expect(resourceDeposits()).toHaveLength(6);expect(heightAt(DEPOT.x,DEPOT.z)).toBeGreaterThan(0);for(const d of resourceDeposits()){expect(routeLength(d.route)).toBeGreaterThan(20);for(let i=1;i<d.route.length;i++){const a=d.route[i-1]!,b=d.route[i]!;expect(b.y).toBeGreaterThan(0);expect(Math.abs(b.y-a.y)/Math.hypot(b.x-a.x,b.z-a.z)).toBeLessThan(.65);}}});
});
