import { makeClouds,makeMountains } from '../../src/world/environment.ts';
import { buildItemThumbnailModel } from '../../src/ui/model-thumbnails.ts';
import { ITEM_IDS } from '../../src/craft/hotbar.ts';
import { FARM } from '../../src/core/constants.ts';
// Capture Wildtag's design proportions and animation pivots as Blender modeling references.
import * as THREE from 'three';
import { gzipSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { buildCritterModel } from '../../src/critters/models.ts';
import { SPECIES } from '../../src/critters/species.ts';
import { PROP_ART_BUILDERS } from '../../src/world/props.ts';
import { buildVillage } from '../../src/village/buildings.ts';
import { buildNpcModel, NPCS } from '../../src/village/npcs.ts';
import { buildCastle, buildGoblin, buildElf, buildCrystal } from '../../src/castle/builders.ts';
import { buildAtlantis, buildDiveMarker, buildClamGuard, buildCrocodile, buildTurtle } from '../../src/underwater/builders.ts';
import { buildDroneMesh } from '../../src/structures/drones.ts';
import { buildTrampMesh } from '../../src/structures/trampolines.ts';
import { geometryFor } from '../../src/structures/build.ts';
import { HandsView } from '../../src/player/hands.ts';
import { buildSign } from '../../src/farm/visuals.ts';
import { mulberry32 } from '../../src/core/rng.ts';
const result=[];
function capture(id,root,category){
 root.updateMatrixWorld(true);const parts=[];
 root.traverse(o=>{if(!(o instanceof THREE.Mesh))return;
  const geo=o.geometry; const pos=geo.getAttribute('position');if(!pos)return;
  const normal=geo.getAttribute('normal'),col=geo.getAttribute('color');
  const mat=Array.isArray(o.material)?o.material[0]:o.material;
  const vectors=(attr)=>attr?Array.from({length:attr.count*3},(_,i)=>i%3===0?attr.getX(Math.floor(i/3)):i%3===1?attr.getY(Math.floor(i/3)):attr.getZ(Math.floor(i/3))):null;
  parts.push({name:`part_${parts.length}`,positions:vectors(pos),colors:vectors(col),normals:vectors(normal),indices:geo.index?Array.from(geo.index.array):null,matrix:o.matrixWorld.toArray(),color:mat.color?.toArray()??[1,1,1],emissive:mat.emissive?.toArray()??[0,0,0],opacity:mat.opacity,roughness:mat.roughness??.75,metalness:mat.metalness??0});
 });
 result.push({id,category,parts});console.log(id,parts.length);
}
for(const sp of SPECIES)capture(`critter_${sp.id}`,buildCritterModel(sp.id,mulberry32(42)).group,'creature');
for(const [key,build]of Object.entries(PROP_ART_BUILDERS))capture(`prop_${key}`,new THREE.Mesh(build(),new THREE.MeshStandardMaterial({vertexColors:true})),'scenery');
capture('village',buildVillage(new THREE.Scene()),'architecture');
for(const npc of NPCS)capture(`npc_${npc.id}`,buildNpcModel(npc).group,'character');
for(const purified of [false,true])capture(purified?'castle_purified':'castle_cursed',buildCastle(new THREE.Scene(),purified),'architecture');
capture('ward_crystal',buildCrystal(false).group,'crystal');
capture('goblin',buildGoblin(mulberry32(42)),'character');capture('elf',buildElf(mulberry32(42)),'character');
capture('atlantis',buildAtlantis(false),'architecture');capture('dive_marker',buildDiveMarker(),'equipment');
capture('clam',buildClamGuard(42).root,'creature');capture('crocodile',buildCrocodile(42).root,'creature');capture('turtle',buildTurtle(42).root,'creature');
capture('drone',buildDroneMesh().group,'equipment');
for(const kind of ['ground','sky'])capture(`trampoline_${kind}`,buildTrampMesh(kind).group,'equipment');
for(const kind of ['wall','ramp','cube'])capture(`build_${kind}`,new THREE.Mesh(geometryFor(kind),new THREE.MeshStandardMaterial({color:0xa79776})),'architecture');
const camera=new THREE.PerspectiveCamera();new HandsView(camera);capture('hands_equipment',camera,'equipment');
capture('farm_sign',buildSign(),'equipment');
capture('zipline_post',new THREE.Mesh(new THREE.CylinderGeometry(.16,.2,1,8)),'equipment');
capture('tracker_dart',new THREE.Mesh(new THREE.CylinderGeometry(.02,.02,.4,6)),'equipment');
for(const item of ITEM_IDS)capture(`item_${item.replace(':','_')}`,buildItemThumbnailModel(item),'equipment');
capture('clouds',makeClouds(),'cloud');capture('mountains',makeMountains(),'scenery');
capture('grapple_hook',new THREE.Mesh(new THREE.ConeGeometry(.26,.8,6)),'equipment');
capture('farm_crate',new THREE.Mesh(new THREE.BoxGeometry(FARM.cubeSize,FARM.cubeSize,FARM.cubeSize)),'equipment');
mkdirSync('art/wildtag',{recursive:true});writeFileSync('art/wildtag/design-reference.json.gz',gzipSync(JSON.stringify(result),{level:9}));
console.log('Captured',result.length,'assets');
